version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "ember",
    "meteor"
  ]
  environment = [
    "nodejs",
    "vitest",
    "jasmine",
    "mongo"
  ]